services:
  - type: web
    name: stocks-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
